[package]
name = "libsvm-wasm-inference"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
libsvm-rs = { path = "../../../../crates/libsvm" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wasm-bindgen = "0.2"

[workspace]
